[package]
name = "smart_contract" # HAS TO BE THE NAME OF THE ROOT DIRECTORY
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = true

[dependencies]
cairo_execute = "2.12.0"
starknet = "2.12.0"
snforge_std = "0.52.0"

# [[target.executable]]
# # A PATH TO THE FUNCTION WITH THE #[executable] ANNOTATION
# # <root-directory>::<file-name>::<function-name>
# function = "smart_contract::playground::main"
